// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI2.Models;

#nullable disable

namespace WebAPI2.Migrations
{
    [DbContext(typeof(VoteDetailContext))]
    partial class VoteDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI2.Models.OptionDetail", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<bool>("OptionIsVote")
                        .HasColumnType("bit");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OptionScore")
                        .HasColumnType("int");

                    b.Property<int?>("VoteDetailId")
                        .HasColumnType("int");

                    b.HasKey("OptionID");

                    b.HasIndex("VoteDetailId");

                    b.ToTable("OptionDetails");
                });

            modelBuilder.Entity("WebAPI2.Models.VoteDetail", b =>
                {
                    b.Property<int>("VoteDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteDetailID"));

                    b.Property<string>("TopicDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VoteDetailID");

                    b.ToTable("VoteDetails");
                });

            modelBuilder.Entity("WebAPI2.Models.OptionDetail", b =>
                {
                    b.HasOne("WebAPI2.Models.VoteDetail", null)
                        .WithMany("OptionDetail")
                        .HasForeignKey("VoteDetailId");
                });

            modelBuilder.Entity("WebAPI2.Models.VoteDetail", b =>
                {
                    b.Navigation("OptionDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
